modLoader="javafml"
loaderVersion="[40,)"
license="LGPLv3"
issueTrackerURL="https://github.com/yungnickyoung/YUNGs-Better-Fortresses/issues"

[[mods]]
    modId="${mod_id}"
    version="${version}"
    displayName="${mod_full_name}"
    credits="Thanks so much to all my patrons!"
    authors="YUNGNICKYOUNG, Acarii"
    description="${mod_description}"
    logoFile="logo.png"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/yungs-better-nether-fortresses"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.0,)"

[[dependencies.${mod_id}]]
    modId="yungsapi"
    versionRange="[${minecraft_version}-Forge-${yungsapi_version},)"
    mandatory=true
    ordering="NONE"
    side="BOTH"